LOCAL lcCAMINHO AS STRING
STORE '' to lcCAMINHO
LOCAL lnDECISAO AS INTEGER
STORE 0 to lnDECISAO

lcCAMINHO = ADDBS(UPPER(ALLTRIM(FULLPATH(CURDIR()))))

IF LEFT(lcCAMINHO,3) == 'D:\' OR UPPER(RIGHT(lcCAMINHO,5)) == '_SVN\' 
	WAIT WIND 'APERTE ESC PARA CANCELAR O UPDATE OU APERTE QUALQUER TECLA PRA CONTINUAR' NOWAIT
	lnDECISAO = INKEY(5)
	*27 = ESC
	IF lnDECISAO == 27
		DO G:\TESTESVF\PLATA\MENURAIZ.PRG
	ENDIF
	
	LOCAL			llSCAN AS Boolean
	STORE .T. TO	llSCAN

	LOCAL loLOCATOR AS 'WBEMScripting.SWBEMLocator'
	LOCAL loWS AS 'WScript.Shell'
	LOCAL loPROC
	LOCAL loWMI

	loWS		= CREATEOBJECT('WScript.Shell')
	loLOCATOR	= CREATEOBJECT('WBEMScripting.SWBEMLocator')

	loWS.Run('"c:\Program Files\TortoiseSVN\bin\TortoiseProc.exe" /command:update /path:"'+lcCAMINHO+'" /closeonend:0')

	WAIT WIND 'EXECUTANDO UPDATE-SVN NA PASTA' NOWAIT

	DO WHILE llSCAN
		loWMI		= loLOCATOR.ConnectServer()
		loWMI.Security_.ImpersonationLevel = 3
		loPROC		= loWMI.ExecQuery("SELECT * FROM WIN32_PROCESS WHERE NAME = 'TortoiseProc.exe'")
		
		IF EMPTY(loPROC.Count)
			llSCAN = .F.
		ENDIF
		
		RELEASE loWMI
	ENDDO

	WAIT CLEAR
ENDIF

DO G:\TESTESVF\PLATA\MENURAIZ.PRG
