/****** Object:  Table [dbo].[TS_PRINTERLIST]    Script Date: 03/22/2011 09:32:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TS_PRINTERLIST](
	[PK_ID] [int] IDENTITY(1,1) NOT NULL,
	[DS_MAQUINA] [varchar](50) NULL,
	[DS_IMPRESSORA] [varchar](120) NULL,
	[FK_OWNER] [int] NULL,
	[DH_INCLUSAO] [smalldatetime] NULL,
	[DH_ALTERACAO] [smalldatetime] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[PK_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TS_PRINTERLIST] ADD  DEFAULT ((0)) FOR [FK_OWNER]
GO


